### ISSUE TITLE
D10.2.1

### ISSUE THREAD

**Issue by limelect** [JensBorrisholt/Hooks#1]
After active pressing any key get 
Access violation
debug at line 61 of main it happens.
P.S once it worked OK

**Comment by JensBorrisholt** [comment]
I can't reproduce it

**Comment by limelect** [comment]
Tried with my new compiler
D10.2.3 same problem
Sorry

**Comment by JensBorrisholt** [comment]
I can't reproduce it

Create me at test application

**Comment by limelect** [comment]
OK the problem is under the debugger !!
If i run your program out of the IDE it works.
You decide how it should work.
In my opinion under the debugger too.
