### ISSUE TITLE
Request for demos

### ISSUE THREAD

**Issue by RicardoOliveira** [JensBorrisholt/Hooks#2]
Hi,
First of all, thank you for this excellent project.
I'm having some trouble getting the hooks to work, specially the mouse hook.
Could you please provide some more examples?

**Comment by JensBorrisholt** [comment]
I'm sorry I totally overlooked this issue. Are a demo application stille relevant?

**Comment by PPP142** [comment]
Hi, do you have an example with TCBTHook?
Thank you.
