### ISSUE TITLE
old Hooks.pas memory leak

### ISSUE THREAD

**Issue by PizzaProgram** [JensBorrisholt/Hooks#5]
Hi,
 I'm using an old Hooks.pas under Delphi 7.
And it's leaking memory on close.
I've searched the web, and found this repo, but it seems completely different.

Do I guess right, that:
 - this repo is not working with D7 any more?
 _(Please add min. version to Readme.md!)_

According to MadExcept report I think the old code is leaking here:
```pascal
procedure FreeHookInstance(ObjectInstance: Pointer);
begin      
  if ObjectInstance = nil then
    Exit;

  pObjectInstance(ObjectInstance)^.Next := InstFreeList;
  InstFreeList := ObjectInstance
end;
```

Because at creation there are lot more things created.

Is there any newer version of Hooks.pas that would still work with D7?

Thanks :-)

**Comment by JensBorrisholt** [comment]
Except from the namespaces in the unit names I don't see why it shouldn't be running under Delphi 7.

**Comment by PizzaProgram** [comment]
OK, I will compare with the new unit line by line, and report back...

**Comment by PizzaProgram** [comment]
Well, sorry, too many changes since my version and the current one.
The new one is using containers <T>. That was not available under D7.

[Hooks.zip](https://github.com/JensBorrisholt/Hooks/files/8749933/Hooks.zip)

![kép](https://user-images.githubusercontent.com/26026089/169708699-fda2fcd4-399f-4940-a987-d3ad842e2c56.png)

**Comment by JensBorrisholt** [comment]
With 20 minuts of efford you can clone the repo and make i work under Delphi 7, I can. In general I don't support thst old compilers, simply because the language where so limited compared to todays standard.

**Comment by PizzaProgram** [comment]
I'm not enough experienced programmer to completely rewrite a container-system.
How do I replace it?
 - array?

**Comment by JensBorrisholt** [comment]
This is a start. Then you can do the rest you self. 
[HooksD7.zip](https://github.com/JensBorrisholt/Hooks/files/8749967/HooksD7r.zip)

But in general Delphi 7 isn't supported.

**Comment by PizzaProgram** [comment]
Thank you VERY much for the quick code!
 _(I've started to implement it 2 minutes after you wrote back, worked 4 hours + 2 today.)_

I'm just reporting back the result:
 - Bad luck: it is much worse than it was before.

# 1. now it's leaking after each keystroke:

![kép](https://user-images.githubusercontent.com/26026089/169770943-7008f44d-87af-4d82-9d5a-1b686f19746d.png)

# 2. Somehow it is calling KeyDown events on the next opening form, while they are just **KeyUPs** !
 (I press a key > a new Form is opening as it should > but the Edit1KeyDown is executed on the newly opened Form the moment I **release** the key.)

```pascal
procedure TMainSegedClass.KeyboardHookPreExecute(Hook: THook; var Hookmsg: THookMessage);
var
    Key: Word;
    ks : TKeyboardState;
    shs: TShiftState;
    f  : TCustomForm;
    pr : TKeyEvent;
    fo : boolean;

begin
    if program_.vege then Exit;
    try
        if Hookmsg.LParam <= 0 then exit;

        f := Screen.ActiveCustomForm;     
        if f = nil then begin // sometimes Screen.ActiveCustomForm gives back NIL!!! 
            h := Windows.GetForegroundWindow();
            for i := 0 to Screen.CustomFormCount-1 do begin
                if Screen.Forms[i].Handle = h then begin
                    f := Screen.Forms[i];
                    break;
                end;
            end;
        end;
        if f = nil then begin
            HookMsg.Result := 1; // kills button
            Exit;
        end;

        fo := (f = MainForm) or (f = Frm_DeskTool ) ; // is this the Main form or it's DeskTool form ?

        if fo then begin
            if MainForm.Visible and MainForm.Enabled then begin
                if GetKeyboardState(ks) = True then
                    shs := KeyboardStateToShiftState(ks)
                else
                    shs := [];
                Key := TLowLevelKeyboardHook(Hook).KeyName.ScanCode; //old code: Hookmsg.WPARAM;
                if TLowLevelKeyboardHook(Hook).LowLevelKeyStates.KeyState = ksKeyDown then
                    MainForm.OnKeyDown(FoForm, Key,  shs );
                //Here you can choose if you want to return the key stroke to the application or not
                Hookmsg.Result := IfThenI(Key = 0, 1, 0);
            end
            else
                Hookmsg.Result := 1;
        end
        else
        if (f is TForm) and assigned(TForm(f).OnKeyDown)
        and (TLowLevelKeyboardHook(Hook).LowLevelKeyStates.KeyState = ksKeyDown) then
        begin
            shs := KeyboardStateToShiftState(ks);
            Key := TLowLevelKeyboardHook(Hook).KeyName.ScanCode; //Hookmsg.WPARAM;
            pr := TForm(f).OnKeyDown;
            pr(f, Key,  shs );

            Hookmsg.Result := IfThenI(Key = 0, 1, 0);
        end
        else
        if (f is TForm) and assigned(TForm(f).OnKeyUp)
        and (TLowLevelKeyboardHook(Hook).LowLevelKeyStates.KeyState = ksKeyUp) then
        begin
            shs := KeyboardStateToShiftState(ks);
            Key := TLowLevelKeyboardHook(Hook).KeyName.ScanCode; //Hookmsg.WPARAM;
            pr := TForm(f).OnKeyUp;
            pr(f, Key,  shs );

            Hookmsg.Result := IfThenI(Key = 0, 1, 0);
        end
        else
            Hookmsg.Result := 0;
    except on e: exception do begin
        HookMsg.Result := 1;
        LOGGOL('KeyboardHookPreExecute hiba:' + E.message);
        end;
    end;
end;
```
Maybe I'll have more free time in 3-4 month to investigate this more.  
Until than I'm forced to revert changes and accept that tiny leak while closing the app.

Many thanks for your help!

**Comment by JensBorrisholt** [comment]
1) I never said that i fixed leeakes. I said it was at good place to start. Did you free the hook on closing? 
2) A Keyboard Hook is applixation wide. A LowLevelKeyboardHook is OS wide.
