### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Marsillio** [JensBorrisholt/Hooks#6]
1.  Open the included demo 
2.  Add ReportMemoryLeaksOnShutdown := True in main form initialization
3.  Run the demo, click Activate, Type some characters, Click Dectivate
4.  Close the demo
5.  Memory leak window appears!

Delphi 11.1 Version 28.0.44500.8973

**Comment by JensBorrisholt** [comment]
I totally overlooked your bug report. It is fixed with the latest commit.
